name = "LearnJulia"
uuid = "96e90086-1ec6-4e2c-818b-31b243074244"
authors = ["Tobias Leigh-Wood <tjleighwood@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
